 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectPC_Store;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Patrick Lirio
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jblCustomerType = new javax.swing.JLabel();
        cbCustomerType = new javax.swing.JComboBox<>();
        BtnExit = new javax.swing.JButton();
        BtnOK3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 27, 27));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 11, 302, 118));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 140));

        jPanel2.setBackground(new java.awt.Color(41, 41, 41));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 23, -1, -1));

        tfName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 23, 207, -1));

        jblCustomerType.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jblCustomerType.setForeground(new java.awt.Color(255, 255, 255));
        jblCustomerType.setText("Customer Type :");
        jPanel2.add(jblCustomerType, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 65, -1, -1));

        cbCustomerType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbCustomerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Member", "Senior", "Regular", "New" }));
        cbCustomerType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCustomerTypeActionPerformed(evt);
            }
        });
        jPanel2.add(cbCustomerType, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 64, 132, -1));

        BtnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnExit.setText("EXIT");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        jPanel2.add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 70, 20));

        BtnOK3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnOK3.setText("OK");
        BtnOK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOK3ActionPerformed(evt);
            }
        });
        jPanel2.add(BtnOK3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 70, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 400, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCustomerTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCustomerTypeActionPerformed

        
        
    }//GEN-LAST:event_cbCustomerTypeActionPerformed
private JFrame frame;
    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
       frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm you want to exit","PC hub",
               JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
            
        }
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnOK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOK3ActionPerformed
        this.dispose();
        Orderingform order = new Orderingform();
        order.setVisible(true);
    }//GEN-LAST:event_BtnOK3ActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnOK3;
    public static javax.swing.JComboBox<String> cbCustomerType;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jblCustomerType;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
